import { createHash } from "node:crypto";
import type { ApplicationBuildPlan } from "./application-contract";
import { buildDefaultExecutor, type BuildResult } from "../builder/executor";
import { transitionBuilderPlan, type BuilderExecutionRecord } from "../builder/engine";
import type { BuilderPlan } from "../builder/types";

export interface GeneratedWorkspaceFile {
  path: string;
  content: string;
}

export interface ApplicationExecutionResult {
  applicationId: string;
  lifecycle: BuilderPlan["status"];
  builderPlan: BuilderPlan;
  records: BuilderExecutionRecord[];
  build: BuildResult;
  workspace: {
    root: string;
    files: GeneratedWorkspaceFile[];
    digest: string;
  };
}

function applicationId(plan: ApplicationBuildPlan): string {
  return createHash("sha256")
    .update(`${plan.tenantId}:${plan.projectId}:${plan.name}:${plan.releaseDigest}`)
    .digest("hex")
    .slice(0, 24);
}

function workspaceFiles(plan: ApplicationBuildPlan): GeneratedWorkspaceFile[] {
  const app = plan.name.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-|-$/g, "") || "application";
  const manifest = JSON.stringify(plan, null, 2);

  return [
    {
      path: "frontend/package.json",
      content: JSON.stringify({
        name: `${app}-frontend`,
        private: true,
        scripts: { build: "next build", start: "next start" },
        dependencies: { next: "15.5.19", react: "18.2.0", "react-dom": "18.2.0" },
      }, null, 2) + "\n",
    },
    {
      path: "frontend/next.config.mjs",
      content: `const backend = process.env.HOARE_BACKEND_URL || "http://127.0.0.1:8080";\n\n/** @type {import("next").NextConfig} */\nconst nextConfig = {\n  async rewrites() {\n    return [{ source: "/api/:path*", destination: backend + "/:path*" }];\n  },\n};\n\nexport default nextConfig;\n`,
    },
    {
      path: "frontend/tsconfig.json",
      content: JSON.stringify({ compilerOptions: { target: "ES2022", strict: true, jsx: "preserve", moduleResolution: "bundler", module: "ESNext" }, include: ["**/*.ts", "**/*.tsx", ".next/types/**/*.ts"] }, null, 2) + "\n",
    },
    {
      path: "frontend/app/layout.tsx",
      content: `export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return <html lang="en"><body>{children}</body></html>;\n}\n`,
    },
    {
      path: "frontend/app/page.tsx",
      content: `export default function Home() {\n  return <main><h1>${plan.name}</h1><p>Generated by HOARE.</p><p>Frontend → /api → HOARE-managed backend.</p></main>;\n}\n`,
    },
    {
      path: "frontend/app/api-contract.ts",
      content: `export const API_BASE = "/api";\nexport const API_CONTRACT_VERSION = "application-api-v1";\n`,
    },
    {
      path: "backend/package.json",
      content: JSON.stringify({
        name: `${app}-backend`,
        private: true,
        scripts: { build: "tsc -p tsconfig.json", start: "node dist/server.js" },
        dependencies: { express: "5.1.0" },
        devDependencies: { typescript: "5.9.3", "@types/express": "5.0.3", "@types/node": "22.15.21" },
      }, null, 2) + "\n",
    },
    {
      path: "backend/tsconfig.json",
      content: JSON.stringify({ compilerOptions: { target: "ES2022", module: "NodeNext", moduleResolution: "NodeNext", outDir: "dist", rootDir: "src", strict: true, esModuleInterop: true, skipLibCheck: true }, include: ["src/**/*.ts"] }, null, 2) + "\n",
    },
    {
      path: "backend/src/server.ts",
      content: `import express from "express";\n\nconst app = express();\napp.use(express.json());\napp.get("/health", (_req, res) => res.json({ ok: true, application: "${app}", contract: "application-api-v1" }));\napp.listen(Number(process.env.PORT ?? 8080), "0.0.0.0");\n`,
    },
    {
      path: "backend/src/routes/health.ts",
      content: `export function health() { return { ok: true, application: "${app}", contract: "application-api-v1" }; }\n`,
    },
    {
      path: "contracts/application-api-v1.ts",
      content: `export interface HealthResponse { ok: boolean; application: string; contract: "application-api-v1"; }\nexport const API_CONTRACT_VERSION = "application-api-v1" as const;\n`,
    },
    {
      path: "database/001_initial.sql",
      content: `create table if not exists application_metadata (\n  id text primary key,\n  tenant_id text not null,\n  project_id text not null,\n  name text not null,\n  release_digest text not null,\n  created_at timestamptz not null default now()\n);\n`,
    },
    {
      path: "deployment/manifest.json",
      content: JSON.stringify({ runtime: "hoare", target: plan.target, application: app, frontend: { path: "frontend", port: 3000, apiPrefix: "/api" }, backend: { path: "backend", port: 8080, healthPath: "/health", public: false }, database: "database" }, null, 2) + "\n",
    },
    {
      path: "application.manifest.json",
      content: `${manifest}\n`,
    },
    {
      path: "README.md",
      content: `# ${plan.name}\n\nGenerated by HOARE Native Application Factory.\n\nFrontend, backend, database, deployment and API contracts are generated as one governed application workspace. The frontend exposes /api through a controlled rewrite to the private backend service.\n`,
    },
  ];
}

function toBuilderPlan(plan: ApplicationBuildPlan): BuilderPlan {
  const resources = [
    { kind: "application" as const, name: `${plan.name}-application`, dependsOn: [] },
    { kind: "api" as const, name: `${plan.name}-api`, dependsOn: [`${plan.name}-application`] },
    { kind: "infrastructure" as const, name: `${plan.name}-runtime`, dependsOn: [`${plan.name}-api`] },
  ];

  return {
    id: applicationId(plan),
    intent: {
      tenantId: plan.tenantId,
      name: plan.name,
      description: "HOARE native application generated from a validated application plan",
      resources: resources.map((resource) => resource.kind),
    },
    resources,
    deployment: {
      provider: plan.target === "owned-runtime" ? "hoare" : plan.target,
      environment: "development",
    },
    status: "planned",
  };
}

export async function executeNativeApplication(
  plan: ApplicationBuildPlan,
): Promise<ApplicationExecutionResult> {
  const builderPlan = toBuilderPlan(plan);
  const records: BuilderExecutionRecord[] = [];

  let transitioned = transitionBuilderPlan(builderPlan, "approve");
  records.push(transitioned.record);
  transitioned = transitionBuilderPlan(transitioned.plan, "start");
  records.push(transitioned.record);

  const executor = buildDefaultExecutor();
  const build = await executor.execute(transitioned.plan);

  transitioned = transitionBuilderPlan(transitioned.plan, "complete");
  records.push(transitioned.record);

  const files = workspaceFiles(plan);
  const workspaceDigest = createHash("sha256")
    .update(files.map((file) => `${file.path}\0${file.content}`).join("\0"))
    .digest("hex");

  return {
    applicationId: builderPlan.id,
    lifecycle: transitioned.plan.status,
    builderPlan: transitioned.plan,
    records,
    build,
    workspace: {
      root: `generated/${plan.tenantId}/${plan.projectId}/${builderPlan.id}`,
      files,
      digest: workspaceDigest,
    },
  };
}
