import { createHash } from "node:crypto";
import type { ApplicationBuildPlan } from "./application-contract";
import { buildDefaultExecutor, type BuildResult } from "../builder/executor";
import { transitionBuilderPlan, type BuilderExecutionRecord } from "../builder/engine";
import type { BuilderPlan } from "../builder/types";

export interface GeneratedWorkspaceFile {
  path: string;
  content: string;
}

export interface ApplicationExecutionResult {
  applicationId: string;
  lifecycle: BuilderPlan["status"];
  builderPlan: BuilderPlan;
  records: BuilderExecutionRecord[];
  build: BuildResult;
  workspace: {
    root: string;
    files: GeneratedWorkspaceFile[];
    digest: string;
  };
}

function applicationId(plan: ApplicationBuildPlan): string {
  return createHash("sha256")
    .update(`${plan.tenantId}:${plan.projectId}:${plan.name}:${plan.releaseDigest}`)
    .digest("hex")
    .slice(0, 24);
}

function workspaceFiles(plan: ApplicationBuildPlan): GeneratedWorkspaceFile[] {
  const app = plan.name.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-|-$/g, "") || "application";

  return [
    {
      path: "frontend/app/page.tsx",
      content: `export default function Home() {\n  return <main><h1>${plan.name}</h1><p>Generated by HOARE.</p></main>;\n}\n`,
    },
    {
      path: "frontend/app/api-contract.ts",
      content: `export const API_BASE = "/api";\nexport const API_CONTRACT_VERSION = "application-api-v1";\n`,
    },
    {
      path: "backend/src/server.ts",
      content: `export const application = ${JSON.stringify({ name: plan.name, tenantId: plan.tenantId, projectId: plan.projectId })};\nexport const apiContractVersion = "application-api-v1";\n`,
    },
    {
      path: "backend/src/routes/health.ts",
      content: `export function health() { return { ok: true, application: "${app}", contract: "application-api-v1" }; }\n`,
    },
    {
      path: "application.manifest.json",
      content: `${JSON.stringify(plan, null, 2)}\n`,
    },
    {
      path: "README.md",
      content: `# ${plan.name}\n\nGenerated by HOARE Native Application Factory.\n\nFrontend and backend are governed by application-api-v1.\n`,
    },
  ];
}

function toBuilderPlan(plan: ApplicationBuildPlan): BuilderPlan {
  const resources = [
    { kind: "application" as const, name: `${plan.name}-application`, dependsOn: [] },
    { kind: "api" as const, name: `${plan.name}-api`, dependsOn: [`${plan.name}-application`] },
    { kind: "infrastructure" as const, name: `${plan.name}-runtime`, dependsOn: [`${plan.name}-api`] },
  ];

  return {
    id: applicationId(plan),
    intent: {
      tenantId: plan.tenantId,
      name: plan.name,
      description: "HOARE native application generated from a validated application plan",
      resources: resources.map((resource) => resource.kind),
    },
    resources,
    deployment: {
      provider: plan.target === "owned-runtime" ? "hoare" : plan.target,
      environment: "development",
    },
    status: "planned",
  };
}

export async function executeNativeApplication(
  plan: ApplicationBuildPlan,
): Promise<ApplicationExecutionResult> {
  const builderPlan = toBuilderPlan(plan);
  const records: BuilderExecutionRecord[] = [];

  let transitioned = transitionBuilderPlan(builderPlan, "approve");
  records.push(transitioned.record);
  transitioned = transitionBuilderPlan(transitioned.plan, "start");
  records.push(transitioned.record);

  const executor = buildDefaultExecutor();
  const build = await executor.execute(transitioned.plan);

  transitioned = transitionBuilderPlan(transitioned.plan, "complete");
  records.push(transitioned.record);

  const files = workspaceFiles(plan);
  const workspaceDigest = createHash("sha256")
    .update(files.map((file) => `${file.path}\0${file.content}`).join("\0"))
    .digest("hex");

  return {
    applicationId: builderPlan.id,
    lifecycle: transitioned.plan.status,
    builderPlan: transitioned.plan,
    records,
    build,
    workspace: {
      root: `generated/${plan.tenantId}/${plan.projectId}/${builderPlan.id}`,
      files,
      digest: workspaceDigest,
    },
  };
}
