import { deploymentRegistry, type DeploymentStatus } from "@/lib/hoare/deployment/deployment-registry";
import { buildAndStartNativeApplication, stopNativeApplication } from "@/lib/hoare/deployment/native-application-runtime";

function tenantIdFrom(request: Request): string | null {
  return request.headers.get("x-tenant-id")?.trim() || null;
}

export async function GET(request: Request, context: { params: Promise<{ id: string }> }) {
  const tenantId = tenantIdFrom(request);
  if (!tenantId) return Response.json({ error: "x-tenant-id is required" }, { status: 400 });

  const { id } = await context.params;
  const deployment = await deploymentRegistry.get(tenantId, id);
  if (!deployment) return Response.json({ error: "deployment not found" }, { status: 404 });
  return Response.json({ data: deployment });
}

export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) {
  const tenantId = tenantIdFrom(request);
  if (!tenantId) return Response.json({ error: "x-tenant-id is required" }, { status: 400 });

  const { id } = await context.params;
  const body = (await request.json()) as {
    status?: DeploymentStatus;
    error?: string;
    action?: "deploy" | "stop";
    description?: string;
    frontend?: { framework?: string; routes?: string[] };
    backend?: { runtime?: string; apiStyle?: "rest" | "rpc" | "graphql" };
    data?: { provider?: string; entities?: string[] };
    target?: "owned-runtime" | "cloudflare" | "cloud" | "edge" | "local";
  };

  const deployment = await deploymentRegistry.get(tenantId, id);
  if (!deployment) return Response.json({ error: "deployment not found" }, { status: 404 });

  if (body.action === "deploy") {
    try {
      const runtime = await buildAndStartNativeApplication(deployment, {
        tenantId,
        projectId: deployment.projectId,
        name: deployment.name,
        description: body.description ?? `Native application generated by HOARE: ${deployment.name}`,
        frontend: body.frontend,
        backend: body.backend,
        data: body.data,
        targets: [body.target ?? "owned-runtime"],
      });
      return Response.json({ data: await deploymentRegistry.get(tenantId, id), runtime }, { status: 200 });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      const failed = await deploymentRegistry.update(tenantId, id, { status: "failed", error: message });
      return Response.json({ error: message, data: failed }, { status: 500 });
    }
  }

  if (body.action === "stop") {
    await stopNativeApplication(tenantId, id);
    return Response.json({ data: await deploymentRegistry.get(tenantId, id) });
  }

  if (!body.status) return Response.json({ error: "status or action is required" }, { status: 400 });

  const updated = await deploymentRegistry.update(tenantId, id, {
    status: body.status,
    error: body.error,
  });
  return Response.json({ data: updated });
}
