import type { ApplicationFactoryInput, ApplicationFactoryPlan, GeneratedArtifact } from "./types";

const slugify = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "hoare-app";

function frontendArtifacts(name: string, slug: string): GeneratedArtifact[] {
  return [
    { path: `app/generated/${slug}/page.tsx`, surface: "frontend", kind: "page", content: `export default function ${name.replace(/[^A-Za-z0-9]/g, "")}Home() {\n  return <main><h1>${name}</h1><p>Generated by HOARE.</p></main>;\n}\n` },
    { path: `app/generated/${slug}/components/AppShell.tsx`, surface: "frontend", kind: "component", content: `export function AppShell({ children }: { children: React.ReactNode }) {\n  return <section data-hoare-app="${slug}">{children}</section>;\n}\n` },
  ];
}
function backendArtifacts(slug: string): GeneratedArtifact[] {
  return [{ path: `app/api/generated/${slug}/route.ts`, surface: "backend", kind: "route", content: `import { NextResponse } from "next/server";\n\nexport async function GET() {\n  return NextResponse.json({ application: "${slug}", status: "ok", generatedBy: "HOARE" });\n}\n` }];
}
function databaseArtifacts(slug: string): GeneratedArtifact[] {
  return [{ path: `migrations/generated/${slug}.sql`, surface: "database", kind: "schema", content: `create table if not exists "${slug.replace(/-/g, "_")}_records" (\n  id uuid primary key default gen_random_uuid(),\n  tenant_id text not null,\n  payload jsonb not null default '{}'::jsonb,\n  created_at timestamptz not null default now()\n);\n` }];
}
export function compileApplicationFactory(input: ApplicationFactoryInput): ApplicationFactoryPlan {
  const slug = slugify(input.plan.intent.name);
  const frontend = frontendArtifacts(input.plan.intent.name, slug);
  const backend = backendArtifacts(slug);
  const database = databaseArtifacts(slug);
  const artifacts = [...frontend, ...backend, ...database];
  const manifest: GeneratedArtifact = { path: `hoare-manifests/${slug}.json`, surface: "deployment", kind: "manifest", content: JSON.stringify({ schema: "hoare.application.v1", application: slug, tenantId: input.plan.intent.tenantId, description: input.description ?? input.plan.intent.description, frontend: { framework: "nextjs", routes: [`/${slug}`] }, backend: { runtime: "nextjs-api", routes: [`/api/generated/${slug}`] }, database: { engine: "postgresql", migrations: [`migrations/generated/${slug}.sql`] }, source: "hoare-builder" }, null, 2) };
  return { id: `factory-${Date.now().toString(36)}`, builderPlanId: input.plan.id, tenantId: input.plan.intent.tenantId, applicationName: input.plan.intent.name, frontend: { framework: "nextjs", routes: [`/${slug}`], components: [`${slug}/components/AppShell`] }, backend: { runtime: "nextjs-api", routes: [`/api/generated/${slug}`], auth: "tenant-jwt" }, database: { engine: "postgresql", tables: [`${slug.replace(/-/g, "_")}_records`] }, artifacts: [...artifacts, manifest], status: "compiled" };
}
